services:


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn usr.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      - DEBUG=FALSE
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MY_SECRET_KEY=${MY_SECRET_KEY}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./selfsigned.key:/etc/nginx/ssl/selfsigned.key
    depends_on:
      - web

volumes:
  mysql_data: