services:


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn usr.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=FALSE
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MY_SECRET_KEY=${MY_SECRET_KEY}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

volumes:
  mysql_data: