services:


  redis:
    image: redis:latest
    networks:
      - app_network

  web:
    image: "sungmin330/usr:version1.0.2"
    command: gunicorn usr.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    expose:
      - "8000"
    depends_on:
      - redis
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DJANGO_ENV=prod
      - ALLOWED_HOSTS=sungminna.com,www.sungminna.com
      - DEBUG=FALSE
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MY_SECRET_KEY=${MY_SECRET_KEY}
      - DB_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}
  nextjs:
    image: "sungmin330/fb-app:version1.0.2"
    expose:
      - "3000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - API_KEY=${NEXT_PUBLIC_API_KEY}
      - AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
      - PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
      - STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
      - MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
      - APP_ID=${NEXT_PUBLIC_APP_ID}
      - MEASUREMENT_ID=${NEXT_PUBLIC_MEASUREMENT_ID}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./selfsigned.key:/etc/nginx/ssl/selfsigned.key
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web
      - nextjs
    networks:
      - app_network
volumes:
  static_volume:
networks:
  app_network:
    driver: bridge